Make TLS support an extras_requires
Yelp/fido pull request #50
Opened 2017-06-02 21:10 UTC by jolynch

This makes it so that the common case (non ssl use) does not need to
depend on pyopenssl, cryptography, etc ... These packages are fragile
and hard to build in general so not having it as a mandatory requirement
is a great idea.

Fixes #49

2017-06-07 21:21 UTC, jnb commented
👍

2017-06-07 21:24 UTC, macisamuele approved these changes
It look reasonable to me ... only concern is about versioning ... this introduces a back incompatible change ... so it would be better to have a major release update
@sjaensch what do you think about?

2017-06-07 21:28 UTC, jolynch commented
@macisamuele I don't think it's backwards incompatible. The library API is not changing, and if you had a requirements.txt (as your application should) you won't break. The next time you re-resolve dependencies you will need to change to fido[tls] if you actually depend on tls, which is pretty reasonable.

2017-06-07 21:33 UTC, macisamuele commented
@jolynch it is more for precaution as it was done for bravado v9.0.0 release.
Having this dependency change should not have specific impact, especially if we're using requirements file; but it is possible that someone in the community is using fido without having the requirements file and we could give him some bad time due to a dependency drop. 😄

2017-06-07 21:38 UTC, jolynch commented
@macisamuele Heh, if someone in the community files a bug I volunteer to close it with "change your dependency to fido[tls]". I can wait though for @jnb or @sjaensch to decide, I don't have a strong opinion.

2017-06-12 11:51 UTC, sjaensch requested changes

2017-06-12 11:51 UTC, sjaensch commented on setup.py
> +            'service-identity'
What about `idna`? It's in the extras_require for twisted[tls].
Also, what about the version restrictions in twisted[tls]? Why are you not copying those?

2017-06-13 07:38 UTC, jolynch commented on setup.py
> +            'service-identity'
Sure, looks like we would have been broken before (I just moved the dependencies out of setup_requires into extras_require, didn't actually check against upstream twisted pins).

I've pinned exactly so we are 100% the same as upstream twisted. What's your opinion on the version question?

2017-06-19 21:37 UTC, jolynch commented
@sjaensch gentle bump

2017-06-21 07:49 UTC, sjaensch approved these changes

2017-06-21 07:49 UTC, merged